; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32cam

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
build_src_filter =
    +<main.cpp>
    +<esp32_cam_controller.cpp>
    +<esp32_rtsp_streamer.cpp>
    -<tcp_cam_streamer.cpp>
    -<dfr1154_*.cpp>

; Monitor and first USB upload
; monitor_speed = 115200
; upload_speed = 115200

; OTA needs two app partitions. The esp32cam board default is huge_app.csv,
; which is fine for serial flashing but not for OTA updates.
board_build.partitions = min_spiffs.csv


upload_protocol = espota
upload_port = 192.168.178.46
upload_flags =
    --auth=1234
    --host_ip=192.168.178.27
    --host_port=3233
    --debug

; DIESE DREI ZEILEN SIND ZWINGEND ERFORDERLICH:
board_build.f_cpu = 240000000L
build_flags =
    -D BOARD_HAS_PSRAM

[dfr1154_base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
    +<dfr1154_main.cpp>
    +<dfr1154_cam_controller.cpp>
    +<dfr1154_server_capture.cpp>
    +<esp32_rtsp_streamer.cpp>
    -<main.cpp>
    -<esp32_cam_controller.cpp>
    -<tcp_cam_streamer.cpp>
lib_deps =
    https://github.com/DFRobot/DFRobot_LTR308.git

[env:dfr1154]
extends = dfr1154_base

[env:dfr1154_ota]
extends = dfr1154_base
upload_protocol = espota
upload_port = dfr1154-cam-01.local
upload_flags =
    --auth=1234

[env:dfr1154_quality_test_ota]
extends = dfr1154_base
build_src_filter =
    +<dfr1154_quality_test.cpp>
    +<dfr1154_camerawebserver.cpp>
    -<main.cpp>
    -<esp32_cam_controller.cpp>
    -<dfr1154_cam_controller.cpp>
    -<dfr1154_server_capture.cpp>
    -<tcp_cam_streamer.cpp>
    -<esp32_rtsp_streamer.cpp>
upload_protocol = espota
upload_port = dfr1154-cam-01.local
upload_flags =
    --auth=1234
